message("CMAKE: Setting up toolchain.")

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)

set(TOOLCHAIN_PREFIX arm-none-eabi-)
find_program(ARM_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)

get_filename_component(ARM_TOOLCHAIN_DIR ${ARM_C_COMPILER} DIRECTORY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")

option(IS_COMPILED_ON_LINUX ON)
if(NOT IS_COMPILED_ON_LINUX)
     set(SYSTEM_POSTFIX .exe)
endif()

set(CMAKE_C_COMPILER ${ARM_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}gcc${SYSTEM_POSTFIX})
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})

set(CMAKE_OBJCOPY ${ARM_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}objcopy${SYSTEM_POSTFIX} CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${ARM_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}size${SYSTEM_POSTFIX} CACHE INTERNAL "size tool")

message("CMAKE: Toolchain set.")
